### ISSUE TITLE
Error on ./site/contrib/build.sh -b experimental -c update

### ISSUE THREAD

**Issue by h2o-commits** [freifunk-mwu/sites-ffmwu#8]
After a 

./site/contrib/build.sh -b experimental -c update

I get an error

--- Updating module 'packages/ffmwu' ---
Initialized empty Git repository in /home/bender/gluon.neu/gluon/packages/ffmwu/.git/
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
make: *** [Makefile:85: update] Fehler 128

**Comment by belzebub40k** [comment]
This should be fixed with the latest commit.
